name: Azure Python 3.7
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.12
    - name: Install dependencies
      run: |
        make install-azure
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
